# NumPy

* http://www.numpy.org/
* 高速なベクトル演算ライブラリ
    * SciPy, matplotlib, pandas, scikit-learn は NumPy を用いることを前提とした設計になっている
    
* http://ipython-books.github.io/featured-01/
    * http://kaisk.hatenadiary.com/entry/2015/02/19/224531 （日本語）

In [3]:
import numpy as np

* `import` ... `as` でモジュールを別名で import できる

## 配列（`numpy.ndarray`）の初期化

### 1 次元配列

In [202]:
xs = np.array([2, 3, 5, 7])
xs

array([2, 3, 5, 7])

In [203]:
type(xs)

numpy.ndarray

In [204]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [205]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [206]:
np.arange(0, 1.0, 0.25)

array([ 0.  ,  0.25,  0.5 ,  0.75])

In [207]:
np.linspace(0, 1.0, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

### 多次元配列

In [209]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [210]:
xs = np.array([[0, 1, 2], [3, 4, 5]])
xs

array([[0, 1, 2],
       [3, 4, 5]])

In [211]:
xs[1, 1]

4

In [212]:
xs[:, 1]

array([1, 4])

In [213]:
xs[0, :]

array([0, 1, 2])

In [214]:
xs.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [215]:
xs.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [216]:
xs.flatten()

array([0, 1, 2, 3, 4, 5])

## ベクトル演算

In [59]:
xs = np.linspace(0, 10.0, 5)
xs

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [60]:
xs + xs

array([  0.,   5.,  10.,  15.,  20.])

In [61]:
xs += xs
xs

array([  0.,   5.,  10.,  15.,  20.])

In [62]:
xs * 2

array([  0.,  10.,  20.,  30.,  40.])

In [63]:
xs ** 2

array([   0.,   25.,  100.,  225.,  400.])

In [66]:
xs[:2] = 999
xs

array([ 999.,  999.,   10.,   15.,   20.])

In [68]:
ys = np.linspace(0, np.pi, 5)
np.sin(ys)

array([  0.00000000e+00,   7.07106781e-01,   1.00000000e+00,
         7.07106781e-01,   1.22464680e-16])

## 行列積

In [88]:
xs = np.array([[1, 2], [3, 4]])
ys = np.array([[5, 6], [7, 8]])
xs * ys

array([[ 5, 12],
       [21, 32]])

* `*` だと要素ごとの積になる

In [89]:
xs.dot(ys)

array([[19, 22],
       [43, 50]])

* `dot` メソッドで行列積になる
* ただし、行列演算については SciPy を使った方が一般に高速である

## 複素数

In [117]:
1j

1j

In [118]:
type(1j)

complex

In [119]:
1j * 1j

(-1+0j)

In [171]:
x = 1.2 + 3.4j
print(x.real)
print(x.imag)
print(x * (5.6 + 7.8j))

1.2
3.4
(-19.8+28.4j)


* Python は標準で複素数 (`complex` 型) を扱える
* 数（整数リテラル・浮動小数点数リテラル）の後に `j` を付けると虚数になる

In [146]:
(1.2 + 3.4j).conjugate()

(1.2-3.4j)

* `conjugate` メソッドで共役複素数が得られる

In [143]:
import cmath

In [144]:
cmath.exp(cmath.pi * 1j)

(-1+1.2246467991473532e-16j)

* `cmath` モジュールに `complex` 用の数学関数が定義されている
    * https://docs.python.org/3/library/cmath.html
    * http://docs.python.jp/3/library/cmath.html

In [196]:
xs = np.linspace(0, np.pi * 1j, 13)
xs

array([ 0.+0.j        ,  0.+0.26179939j,  0.+0.52359878j,  0.+0.78539816j,
        0.+1.04719755j,  0.+1.30899694j,  0.+1.57079633j,  0.+1.83259571j,
        0.+2.0943951j ,  0.+2.35619449j,  0.+2.61799388j,  0.+2.87979327j,
        0.+3.14159265j])

In [198]:
ys = np.exp(xs)
for i, x in enumerate(ys):
    print("exp({0:2d}iπ/12) = {1: 2.5f} + {2: .5f}i".format(i, x.real, x.imag))

exp( 0iπ/12) =  1.00000 +  0.00000i
exp( 1iπ/12) =  0.96593 +  0.25882i
exp( 2iπ/12) =  0.86603 +  0.50000i
exp( 3iπ/12) =  0.70711 +  0.70711i
exp( 4iπ/12) =  0.50000 +  0.86603i
exp( 5iπ/12) =  0.25882 +  0.96593i
exp( 6iπ/12) =  0.00000 +  1.00000i
exp( 7iπ/12) = -0.25882 +  0.96593i
exp( 8iπ/12) = -0.50000 +  0.86603i
exp( 9iπ/12) = -0.70711 +  0.70711i
exp(10iπ/12) = -0.86603 +  0.50000i
exp(11iπ/12) = -0.96593 +  0.25882i
exp(12iπ/12) = -1.00000 +  0.00000i


* NumPy の配列 (`ndarray`) と数学関数は複素数にも対応している

## 例：Sieve of Eratosthenes

### `list` 版

In [102]:
import math

def eratosthenes_list(size):
    if size == 0:
        return []
    sieve = [True] * size
    sieve[:2] = [False, False]
    root = int(math.sqrt(size - 1)) + 1
    for i in range(2, root):
        if sieve[i]:
            for j in range(i * i, size, i):
                sieve[j] = False
    return sieve[:size]

eratosthenes_list(10)

[False, False, True, True, False, True, False, True, False, False]

In [83]:
def count_primes(n, sieve):
    counter = 0
    for b in sieve(n + 1):
        if b:
            counter += 1
    return counter

def show_primes(n, sieve):
    for i, b in enumerate(sieve(n + 1)):
        if b: 
            print(i, end = ' ')

In [84]:
show_primes(100, sieve=eratosthenes_list)

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

In [85]:
count_primes(10000000, sieve=eratosthenes_list)

664579

In [86]:
%timeit eratosthenes_list(10000000)

1 loop, best of 3: 3.21 s per loop


### `numpy.ndarray` 版

In [87]:
def eratosthenes_numpy(size):
    if size == 0:
        return []
    sieve = np.ones(size, dtype=bool)
    sieve[:2] = False
    root = int(np.sqrt(size - 1)) + 1
    for i in range(2, root):
        if sieve[i]:
            sieve[i * i : size : i] = False
    return sieve[:size]

eratosthenes_numpy(10)

array([False, False,  True,  True, False,  True, False,  True, False, False], dtype=bool)

In [88]:
show_primes(100, sieve=eratosthenes_numpy)

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

In [91]:
count_primes(10000000, sieve=eratosthenes_numpy)

664579

In [92]:
%timeit eratosthenes_numpy(10000000)

10 loops, best of 3: 36 ms per loop


In [101]:
print(str(3.21 // 36e-3) + ' 倍の高速化')

89.0 倍の高速化
